### ISSUE TITLE
Rewrite it in rust

### ISSUE THREAD

**Issue by jorgeparavicini** [hugo-andriamaromanana/philomathia#1]
Rust is the superior language. We should rewrite it

**Comment by hugo-andriamaromanana** [comment]
Fuck you Jorge

*Hugo ANDRIAMAROMANANA*
Realest Nigga
@LaPlateforme.io <http://laplateforme.io/>
*04.84.89.52.55*

*Le Campus Méditerranéen du Num**érique*

Le mar. 7 nov. 2023 à 08:38, jorgeparavicini ***@***.***> a
écrit :

**Comment by hugo-andriamaromanana** [comment]
We have to live the python life or i'm getting a zero...
